# jenkins-tryout
# this is the entrypoint of the docker-compose prpject

include:
  - path: ./gemini_agent_1.yml

networks:
  default:
    name: common_network
    external: true

  commont_network1:
    name: commont_network1
    external: true
