FROM ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

# title
ENV TITLE=Chromium

# # replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN rm -f /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install -qqy wget git curl xz-utils

# Install Node.js 20 directly from binary
RUN wget https://nodejs.org/dist/v20.17.0/node-v20.17.0-linux-x64.tar.xz && \
    tar -xJf node-v20.17.0-linux-x64.tar.xz -C /usr/local --strip-components=1 && \
    rm node-v20.17.0-linux-x64.tar.xz && \
    npm install -g yarn
# && npm config set registry https://registry.npmmirror.com/ \

# Install Chrome
RUN cd /tmp && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN cd /tmp && apt-get install -qqy ./google-chrome-stable_current_amd64.deb
RUN rm -f /tmp/google-chrome-stable_current_amd64.deb

RUN npm i -g yarn

# Set up the working directory
WORKDIR /app

# ports and volumes
EXPOSE 3000

VOLUME /config

#  ---
RUN apt-get update
RUN apt-get install -qqy openjdk-17-jdk
RUN apt-get install -qqy psmisc

# ---
ENV CONDA_PLUGINS_AUTO_ACCEPT_TOS=true
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O install_miniconda.sh && \
  bash install_miniconda.sh -b -p /opt/conda && rm install_miniconda.sh
ENV PATH="/opt/conda/bin:${PATH}"

RUN conda install python~=3.11.0 pip && \
    pip install --no-cache-dir requests && \
    conda clean --all
